name: CI/CD Deploy

#on:
 # push:
  #  branches: [ main ]

#on:
  #workflow_dispatch:  # Ce déclencheur te permet de le lancer manuellement depuis GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/quiz-app .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/quiz-app

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            docker stop quiz-app || true
            docker rm quiz-app || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/quiz-app
            docker run -d -p 3038:3000 --name quiz-app ${{ secrets.DOCKER_USERNAME }}/quiz-app
